- hosts: app*
#  strategy: debug
  become: true
  become_method: sudo
  vars:
   document_root: /vagrant

  roles:
   - create_users

  handlers:
    - name: reload apache
      service: name=apache2 state=reloaded

  tasks:
    - name: update apt cache
      apt: update_cache=yes

    - include: tasks/apache.yml

    - name: install php
      apt: name={{ item }} state=present
      with_items:
       - php5
