- hosts: db*
  #strategy: debug
  become: true
  become_method: sudo
  vars:
   document_root: /vagrant

  roles:
   - create_users

  tasks:
    - name: update apt cache
      apt: update_cache=yes

    - name: install mysql
      apt: name={{ item }} state=present
      with_items:
       - mysql-server
